from resources.registerAuth import *
from resources.loginAuth import *
from resources.logoutAuth import *
from resources.addLog import *
from resources.getPatientLog import *
from resources.addPersonalData import *
from resources.getPersonalData import *
from resources.addReminder import *
from resources.addDiagnosis import *
from resources.addMedicine import *
from resources.getMedicine import *